### ISSUE TITLE
get_counts not able to handle non-integer sample frequencies

### ISSUE THREAD

**Issue by vincentvanhees** [jhmigueles/actilifecounts#4]
When I apply get_counts to a 85.7 Hertz GENEActiv recording I get error:

> Error in rep(0, upsample_factor * n * m) : invalid 'times' argument

Does this mean the function assumes an integer sample rate?

**Comment by jhmigueles** [comment]
Hi @vincentvanhees, do you have any sample GENEActiv file at 85.7 Hz you can share? I am trying to fix this.

**Comment by vincentvanhees** [comment]
thanks, I just emailed you a file

**Comment by jhmigueles** [comment]
This should be now fixed in this [branch](https://github.com/jhmigueles/actilifecounts/tree/issue4_nonIntegerSF). Can you try this out? If this works for you, I will merge this into master and submit a new version to CRAN.

**Comment by vincentvanhees** [comment]
@jhmigueles I can confirm that this work, nice!
